import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../componentes/NavBar/NavBar";
import Footer from "../../componentes/Footer/Footer";
import { AppContextProvider } from "../../contexts/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TP-2-Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppContextProvider>
        <Navbar />
        {children}
        <Footer/>
        </AppContextProvider>
      
      </body>
    </html>
  );
}
